# SPDX-FileCopyrightText: 2023 Matthew Nickson < mnickson@sidingsmedia.com >
# SPDX-License-Identifier: CC0-1.0

name: PyTest
on: push

jobs:
  auto-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Cache poetry install
        uses: actions/cache@v2
        with:
          path: ~/.local
          key: poetry-1.3.1-0
      
      - name: Install poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.3.1
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Cache dependancies
        id: cache-deps
        uses: actions/cache@v2
        with:
          path: .venv
          key: pydeps-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependancies
        run: poetry install --no-interaction --no-root
        if: steps.cache-deps.outputs.cache-hit != 'true'

      - name: Install project
        run: poetry install --no-interaction

      - name: Run PyTest
        run: poetry run pytest

      

